# Environment Setup

In [1]:
# Debugging: Use to toggle on/off print statements for debugging.
# True: debug_messages will print 
# False: debug_messages will not print.
DEBUG = False
PACKAGES_INSTALLED = True # Set to True once packages are installed so they don't rerun.

def debug_print(*args, **kwargs):
# print(message)
    if DEBUG:
        print(*args, **kwargs)

def debug_display(df, name=None):
# display(df)
    if DEBUG:
        if name:
            print(f"Displaying DataFrame: {name}")
        display(df)

# When working on a code cell use normal print() / display statements. After you confirm the code is correct, change to the debug versions.

In [2]:
# Install packages

if not PACKAGES_INSTALLED:
    # Install packages
    %pip install -r requirements.txt
    debug_print("Packages installed.")
    PACKAGES_INSTALLED = True
else:
    debug_print("Packages already installed. Skipping installation.")

In [3]:
# Import packages + load dataframe
import pandas as pd
import numpy as np

# Load CSV file into DataFrame
df = pd.read_csv('pro_data.csv')


/var/folders/v1/rpt43fxj323_cj0c2q98_b7r0000gn/T/ipykernel_61869/3357598382.py:6: DtypeWarning: Columns (82,83,84,85,86,87,88) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('pro_data.csv')


# Model Training

In [4]:

# Check the unique values of columns 78-84
for col in df.columns[77:84]:  # Columns are 0-indexed, so column 78 is at index 77
    print(f"Column {col} unique values: {df[col].unique()[:10]}")  # Displaying the first 10 unique values


Column Q95 unique values: [ 2  0  3  1 30  9 15  5 10  4]
Column Q96 unique values: [1 2]
Column Q97 unique values: [30  2  0  1  3  4 23  6 10  9]
Column Q98 unique values: [2 1]
Column Q99 unique values: [ 2  0 15  3 30  5  1  4  6 10]
Column Q101 unique values: ['2' '1' 'Z' 2 1]
Column Q102 unique values: ['6' '2' '3' '1' '5' '4' 'Z' 2 6 1]


In [6]:
import pandas as pd

# Assuming you have already loaded the dataframe as df
# Loop through each column and display its unique values, one per line
for col in df.columns:
    print(f"Unique values in column '{col}':")
    print(df[col].unique())
    print("\n")  # Adds an empty line between columns for better readability


Unique values in column 'Q1':
[ 5  4  6  1 10  9  8  7  3 11  2]


Unique values in column 'Q2':
["['2']" "['1']"]


Unique values in column 'Q3':
[2 1 3 7 6 5 8 4]


Unique values in column 'Q6':
[1 2]


Unique values in column 'Q7':
[ 6  1  5  9  8  7  4  3 11 10  2 12]


Unique values in column 'Q8':
[1 6 4 2 3 5]


Unique values in column 'Q9':
[ 0 30  4  1 20 10 15  2  5  3  7 25 22 26  6 18 27 29 14 13  9 12 28 24
 23  8 17 11 16 21 19]


Unique values in column 'Q10':
[4 5 1 2 6 7 3]


Unique values in column 'Q13':
[2 4 1 3]


Unique values in column 'Q15':
["['2']" "['Q15_other']"]


Unique values in column 'Q16':
[2 3 1]


Unique values in column 'Q17':
[2 3 1]


Unique values in column 'Q19':
[2 1 3]


Unique values in column 'Q20':
[2 1 3]


Unique values in column 'Q23':
[2 5 1 6 3 4]


Unique values in column 'Q25':
[2 1]


Unique values in column 'Q26':
[2 5 3 4 1]


Unique values in column 'Q27':
[2 1 5 4 3]


Unique values in column 'Q28':
[2 5 1 6 4 3]


Unique values

1. ### Random Forest Model